### ISSUE TITLE
[P0]Inheritance definition in yaml

### ISSUE THREAD

**Issue by hellosnow** [ericholscher/sphinx-docfx-yaml#5]
For inheritance tree, it's better to define as below expected behavior (our original proposal). The reason is, we could define the data structure as strong type for easier deserialization, and most important is we could mark the type as customized attribute [UniqueIdentityReference] for resolving.

For example, if the inheritance tree is as below:

X   Y
 \  /
  M    N
     \ /
      A

Expected inheritance tree for A:
```yaml
type: A
inheritance:
- type: M
  inheritance:
  - type: X
  - type: Y
- type: N
```

Our deserialization code in csharp:
```csharp
public class InheritanceTree
{
       [UniqueIdentityReference]
       public string Type { get; set; }
       public List<InheritanceTree> Inheritance { get; set; }
 }
```

**Comment by ericholscher** [comment]
Believe the latest version does this:

```
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: example.multiple_inheritance.Third
    - type: builtins.object
    type: example.multiple_inheritance.ArbitraryWidget
  - inheritance:
    - type: builtins.object
    type: example.multiple_inheritance.Subject
```
