### ISSUE TITLE
[P0] Change return type to a array

### ISSUE THREAD

**Issue by superyyrrzz** [ericholscher/sphinx-docfx-yaml#7]
"return" is expected to share the same model with "parameter". return.type is expected to be an array.

before:
```yml
  syntax:
    return:
      description: all axes
      type: Axis
```
expected:
```yml
  syntax:
    return:
      description: all axes
      type: 
      - Axis
```

**Comment by ericholscher** [comment]
Believe this should also be fixed:

```
    return:
      description: That the method is okay
      type:
      - boolean
```
